# Generated by Django 2.1.7 on 2019-03-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_digitadada_pelo_usuario', models.IntegerField(default=0)),
                ('preco_digitado_pelo_usuario', models.FloatField(default=0.0)),
                ('produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='referencia_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido'),
        ),
    ]
