# Generated by Django 2.1.7 on 2019-03-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rentabilidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
