# Generated by Django 2.1.7 on 2019-03-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_rentabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco_digitado_pelo_usuario',
            field=models.DecimalField(decimal_places=2, default=550000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade_digitadada_pelo_usuario',
            field=models.IntegerField(default=1),
        ),
    ]
