# Generated by Django 2.1.7 on 2019-03-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190306_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco_digitado_pelo_usuario',
            field=models.FloatField(default=550000),
        ),
    ]
