# Generated by Django 2.1.7 on 2019-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190317_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco_digitado_pelo_usuario',
            field=models.DecimalField(decimal_places=2, default=550000.0, max_digits=20),
        ),
    ]
